[package]
edition = "2021"
name = "poker"
version = "1.1.0"

[lib]
test = false
doctest = false

[dependencies]
itertools = "0.12.0"
strum = { version = "0.25.0", features = ["strum_macros", "derive"] }
