[package]
edition = "2021"
name = "sum-of-multiples"
version = "1.5.0"

[lib]
test = false # tests do not live in lib itself,
doctest = false # and doctests are unnecessary

[dependencies]
itertools = "0.12.0"
