[package]
edition = "2021"
name = "acronym"
version = "1.7.0"

[lib]
test = false # tests do not live in lib itself,
doctest = false # and doctests are unnecessary

[dependencies]
itertools = "0.12.0"