[package]
edition = "2021"
name = "bowling"
version = "1.2.0"

[lints.clippy]
new_without_default = "allow"

[lib]
test = false # tests do not live in lib itself,
doctest = false # and doctests are unnecessary

[dependencies]
itertools = "0.12.0"